### ISSUE TITLE
Incorrect zero gmt offset in header

### ISSUE THREAD

**Issue by a-biardi** [libesmtp/libESMTP#11]
I believe I have found a bug in the "Date:" header produced by libesmtp.

My use case is syslog-ng, which uses libesmtp but does not supply a "Date:" header on its own, so libesmtp does it in its place before handing the message over to my local MTA.

My timezone is Europe/Dublin and the local time, at this time of the year (winter time), corresponds to GMT, therefore the difference is 0000.

What I am observing is that libesmtp fills in a header ending in "-0000" (i.e., for the GMT offset). I would expect to see "+0000" instead.

RFC2822 says:

Though "-0000" also indicates Universal Time, it is used to indicate that the time was generated on a system that may be in a local time zone other than Universal Time and therefore indicates that the date-time contains no information about the local time zone.

I believe the following line in `rfc2822date.c`: 

`
dir = (minutes > 0) ? '+' : '-';
`

should actually be:

`
dir = (minutes >= 0) ? '+' : '-';
`

(the above applies to the 1.0.6 version of libesmtp, which is what I am using, but I see that 1.1.0 uses the same logic when not using strftime() (! HAVE_STRFTIME)

Also, I would like to point out that having strftime() does not necessarily guarantee that the implementation supports "%z" (see https://pubs.opengroup.org/onlinepubs/000095399/functions/strftime.html; there is also a corner case whereby "%z" could lead to no characters at all in the output, in which case adding "-0000" would be the correct thing to do).

**Comment by libesmtp** [comment]
Hmm, that should be a `+`, the comparison should indeed be `>=`.  I'm surprised this has not been noticed before since that code has been unchanged since about 2001.

Note that although the source file is called rfc2822date.c RFC 2822 is obsoleted by RFC 5322. The sentence before the one you quote is actually the crucial one:
>    The form "+0000" SHOULD be used to indicate a time zone at Universal Time.

As far as I can tell strftime() has supported `%z` since at least Posix.1-2001 and SUSv2. I have not encountered a system that does not have it, at least in the last 15 years or so, but since there is a possibility that %z might be empty, the easiest thing to do is not use strftime() at all. I'll fix meson.build for this.

**Comment by a-biardi** [comment]
Thanks for looking into this, much appreciated; I referenced the older RFC but as you pointed out the newer 5322 uses the same wording.

Regarding `%z`, I'm aware that it's been around for a long while, and it most likely is supported on every GNU/Linux and BSD box around. But looking around in other sources (mailx, s-nail, postfix for example) it seems like everybody tries to avoid relying on extensions such as `tm->tm_gmtoff` and `strftime()`'s `%z` for maximum portability, if that's what you're interested in.

Final question, I know 1.0.6 is very old and possibly unmaintained but wanted to doublecheck if you're planning to backport a fix to that version as well, or if I should put together a patch and submit to Slackware and FreeBSD (these are the systems I use).

**Comment by libesmtp** [comment]
My preferred approach is to code to standards and if necessary selectively use workarounds for non-compliant implementations. Things like tm_gmtoff GNU extensions are something of a de-facto facto standard and their implementations have more eyes across them than self-coded workarounds, so I see no harm preferring them where available.

I strongly encourage all users to move people away from 1.0.6 and adopt 1.1.0 - it is indeed very old and I no longer support it. Version 1.1.0 is not so different but it is the basis of future development; it maintains ABI compatibility - if it does break, that's a bug with the exception of undocumented internal APIs not prefixed with `smtp_`.

I want to extend the API where necessary to support language bindings (e.g. C++, Python) and to improve support for authentication, i.e. more SASL mechanisms etc. I've already done some ground work for this so backports are a distraction from limited time I do have available for this.

**Comment by libesmtp** [comment]
Looking at bit more at this, a few issues become apparent:

* as pointed out above `strftime()` sets `%z` to an empty string when the time zone cannot be determined.
* the Posix and SUS (X/OPEN) standards do not specify a way to determine if the time zone is known.
* in a `struct tm` the field `tm_isdst` is set less than zero if it is unknown whether daylight saving (summer) time is in effect, this does not necessarily mean the offset from UTC is unknown.
* the values of the global `tzname[]` are unspecified before `tzset()` is called (explicitly or implicitly).
* if the environment variable TZ is unset the time zone might still be set from a system dependent file.

It follows that there is no reliable way to determine of the offset from UTC is unknown.

I reckon the reason the incorrect offset passed unnoticed is that most libESMTP builds will have used `strftime()` and that the implementation of GNU libc will almost certainly have a valid time zone set (even if it is the wrong one).  Nevertheless, despite the strftime code having been added 20 years ago, I feel that the strftime option should be removed and rely instead on the explicitly formatted version using snprintf(). This has the added benefit of not being potentially affected by locale. Also, a number of `strftime()` implementations assume that `tm_isdst < 0` means the offset is unknown so rfc2822date() is updated to do the same. A few other minor simplifications to this code are also possible.

An update to rfc2822date.c is ready for testing. I'll commit to master and the 1.1 branch when satisfied it is correct.

**Comment by libesmtp** [comment]
Fix committed to master and libesmtp-1.1 branches.
