### ISSUE TITLE
setting subject in mail-file.c example doesn't take effect

### ISSUE THREAD

**Issue by woodz-** [libesmtp/libESMTP#15]
For some reason setting a subject via `-s mysubject` on the command line doesn't get propagated into the final mail.

The subject always stays empty.

I tested it by modifying the `test-mail` file and put into the header `Subject: mysubject`, which did the job.

Now it is possible to override the subject from command line. Will it be required to have a subject specification in the template file? Or is there any possibility to set the subject via the lib without having it predefined in the template file `test-mail`?

Can you confirm that behaviour?

Greetings woodz

**Comment by libesmtp** [comment]
Unable to reproduce - commit ac200c9.  Using nc to manually emulate the MSA gives the following
MSA
```
$ sudo netcat -l 587
[sudo] password for brian: 
220 ready
EHLO flaptop
200 ok
MAIL FROM:<brian@flaptop>
200 ok
RCPT TO:<test@flaptop>
200 ok
DATA
350 go ahead
MIME-Version: 1.0
Content-Type: text/plain;
  charset=iso-8859-1
Content-Transfer-Encoding: 7bit
Date: Mon, 17 Oct 2022 22:10:42 +0100
From: brian@flaptop
Message-Id: <1665949150.139913.24515@flaptop>
To: test@flaptop
Subject: Hi there

Hello world!
...
..
...This is a test
..More lines

End of test---
.
200 ok
QUIT
200 ok
brian@flaptop:~/src/libESMTP/libesmtp$ 
$
```
Edit: cut and pasted wrong example 1st time

mail-file/libESMTP
```
$ builddir/examples/mail-file -h localhost -f brian@flaptop -s 'Hi there' -m  examples/test-mail test@flaptop 
S: 220 ready
C: EHLO flaptop
S: 200 ok
C: MAIL FROM:<brian@flaptop>
S: 200 ok
C: RCPT TO:<test@flaptop>
S: 200 ok
C: DATA
S: 354 go ahead
H: MIME-Version: 1.0
H: Content-Type: text/plain;
  charset=iso-8859-1
H: Content-Transfer-Encoding: 7bit
H: Date: Sun, 16 Oct 2022 20:39:10 +0100
H: From: brian@flaptop
H: Message-Id: <1665949150.139913.24515@flaptop>
H: To: test@flaptop
H: Subject: Hi there
S: 200 ok
C: QUIT
S: 200 ok
200 ok
test@flaptop: 200 ok
$
```
Correct/observed behaviour (for non-special headers - see headers.c)  is to ignore headers set via API if already present in the message headers unless the Hdr_OVERRIDE option is set. mail-file.c always sets Hdr_OVERRIDE for Subject:.

**Comment by woodz-** [comment]
But what, if the subject is not there at all. `test-mail` does not contain a subject spec. So there is nothing to be overridden.
Also see my [PR.](https://github.com/libesmtp/libESMTP/pull/16)

**Comment by libesmtp** [comment]
Headers specified via the API do not need to be present in the message to
be output. The trace above shows the Subject: header has been output
despite not being present in the message.

**Comment by woodz-** [comment]
Well OK, then there must be differences between MTAs.
Is there any spec like RFC, ISO or something, which ist telling about the handling of the subject? Could there be different implementations?

One thing I know and experience is, that, when you leave out the from address `-f` option, some MTAs accept it and go for delivery, some others don't deliver at all (without informing the sender).

Could there be something similar with the subject?

**Comment by libesmtp** [comment]
I still cannot reproduce.

The documentation at libesmtp.github.io contains a comprehensive set of references to RFCs used in the design of libESMTP. Also check the FAQ which may be of help. The header code has been stable for almost 2 decades and in the last decade the only significant change is to add documentation comments so it seems unlikely it's a problem now.

I also verified that the Subject header also works with chunking (BDAT) which is the only real difference in header handling that could be affected by the MSA. 

```
$ sudo netcat -l 587
[sudo] password for brian: 
220 greetings
EHLO flaptop
250-flaptop greets you
250-CHUNKING
250 ok
MAIL FROM:<brian@flaptop>
200 ok
RCPT TO:<test@flaptop>
200 ok
BDAT 246
MIME-Version: 1.0
Content-Type: text/plain;
  charset=iso-8859-1
Content-Transfer-Encoding: 7bit
Date: Mon, 17 Oct 2022 22:35:32 +0100
From: brian@flaptop
Message-Id: <1666042532.179411.4635@flaptop>
To: test@flaptop
Subject: Hi there

200 ok
BDAT 70
Hello world!
..
.
..This is a test
.More lines

End of test---
200 ok
BDAT 0 LAST
200 ok
QUIT
200 ok
$
```

libESMTP protocol trace
```
$ builddir/examples/mail-file -h localhost -f brian@flaptop -s 'Hi there' -m  examples/test-mail test@flaptop 
S: 220 greetings
C: EHLO flaptop
S: 250-flaptop greets you
S: 250-CHUNKING
S: 250 ok
C: MAIL FROM:<brian@flaptop>
S: 200 ok
C: RCPT TO:<test@flaptop>
S: 200 ok
H: MIME-Version: 1.0
H: Content-Type: text/plain;
  charset=iso-8859-1
H: Content-Transfer-Encoding: 7bit
H: Date: Mon, 17 Oct 2022 22:35:32 +0100
H: From: brian@flaptop
H: Message-Id: <1666042532.179411.4635@flaptop>
H: To: test@flaptop
H: Subject: Hi there
200 ok
test@flaptop: 200 ok
$
```
I'd suggest to build the most recent commit to master **unmodified** and use the -m/--monitor option to mail-file to check that the subject is actually transmitted with the test message as in the examples above and post the output here (remove any passwords or other authentication). There is no need to install - a  command similar to the above above is sufficient after building with meson/ninja.

**Comment by woodz-** [comment]
I need to admit, everything is working today. Sorry to bother you. It could have been the missing `-f` option when I started playing with the sample.
By the way, is there a sample command line anywhere in the doc for quick starters?

**Comment by libesmtp** [comment]
ok, that's good.

The -f option will not affect Subject header processing, that feeds into 
the From: header and the sender used in the SMTP 'MAIL FROM<>' verb.  
Some MTA/MSAs may reject empty angle brackets depending on local policy.

Only doc on the example app is mail-file --help.  Note that this app is 
intended only as an example of typical API use.  Rest of documentation 
is in the web pages.

**Comment by woodz-** [comment]
Thanks for your response.

Yes, `-f` is independent of subject.

If you wouldn't mind, I would suggest to put a sample command line like the one below into read-the-doc.

### Unencrypted

    $ builddir/examples/mail-file -h localhost -f <from address>@<domain> -s 'Hi there' -m  examples/test-mail <to-address>@<domain>

### Encrypted

    $ builddir/examples/mail-file -h <mailhost.your.domain>:<secure-port> -f <from address>@<domain> -s 'Hi there' -m  examples/test-mail <to-address>@<domain>
