### ISSUE TITLE
projects integrating version 1.0.6 will fail when working with version 1.1.0 

### ISSUE THREAD

**Issue by tru7** [libesmtp/libESMTP#8]
Version 1.0.6 provided libesmtp-config while version now provides libesmtp-1.0.pc instead.
I know pkg-config is the way to go but at same time this will force all projects to rework their build settings and therefore prevent adopting the new version.
Would it be an option to add libesmtp-config for backwards compatibility?
BTW: why is it called libesmtp-1.0.pc? Shouldn't it be just libesmtp.pc instead?

**Comment by libesmtp** [comment]
See https://github.com/libesmtp/libESMTP/wiki/Config-script
It is better to migrate to pkg-config. I don't have time to investigate whether libesmtp-config will work correctly in all circumstances, for example when cross-compiling, so it is removed instead.

Version number is because if there is a ever libESMTP-2.x.x, the API will be incompatible so both versions of the .pc file may be necessary.

**Comment by tru7** [comment]
I understand your point. However every distribution adopting the new release will instantly fail building the packages depending on libesmtp because those projects rely on libesmtp-config. Now what will they do? Stay away from the new release or throw in the wiki patch themselves or waive the depending packages?
The depending projects probably won't notice as long as the libesmtp-dev package provides the 1.0.6 version and so they won't prepare for version 1.1.0 without libesmtp-config.
Looks like a dilemma to me without libesmtp-config.

**Comment by libesmtp** [comment]
I'd be surprised if this was sufficient cause to abandon libESMTP, but I suppose you can't please everyone.  It is a small, documented, well understood change bringing it into line with many other projects which have already done so.

To be clear **1.0.6 is dead**. It should have been dead years ago. **Do not use it**.

**Comment by tru7** [comment]
Personally I can deal with it. But some major linux distributors like Debian and Ubuntu officially provide some patched libesmtp-dev
